version: "3.7"

services:
  mongo:
    image: mongo
    container_name: "bananadb"
    restart: always
    ports:
      - "172.17.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  fastapi-app:
    build: .
    container_name: "auth-app"
    restart: always
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - mongo
