version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "172.17.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
